export const RESOLUTION_IDS = {
  DASHBOARD_BUNDLE_FALLBACK: 'INVESTO-20260629-DASHBOARD-BUNDLE-FALLBACK',
  DASHBOARD_SHELL_LOGO_COMPAT: 'INVESTO-20260629-DASHBOARD-SHELL-LOGO-COMPAT',
  BILLING_SUBSCRIPTION_BACKFILL: 'INVESTO-20260629-BILLING-SUBSCRIPTION-BACKFILL',
  AUTH_BRAND_RESTORE: 'INVESTO-20260629-AUTH-BRAND-RESTORE',
  ACTUAL_LOGO_ASSET: 'INVESTO-20260629-ACTUAL-LOGO-ASSET',
} as const;
