export const RESOLUTION_IDS = {
  DASHBOARD_BUNDLE_FALLBACK: 'INVESTO-20260629-DASHBOARD-BUNDLE-FALLBACK',
  BILLING_SUBSCRIPTION_BACKFILL: 'INVESTO-20260629-BILLING-SUBSCRIPTION-BACKFILL',
} as const;
