export const RESOLUTION_IDS = {
  DASHBOARD_BUNDLE_FALLBACK: 'INVESTO-20260629-DASHBOARD-BUNDLE-FALLBACK',
  BILLING_SUBSCRIPTION_BACKFILL: 'INVESTO-20260629-BILLING-SUBSCRIPTION-BACKFILL',
  PAYMENT_LOCKOUT: 'INVESTO-20260629-PAYMENT-LOCKOUT',
  CASHFREE_ACTIVATION: 'INVESTO-20260629-CASHFREE-ACTIVATION',
} as const;
